name: Gatsby Deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email raianknight@gmail.com
          git config --global user.name RaiaN
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Install dependencies
        run: |
          yarn
      - name: Gatsby build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
