name: Gatsby Deploy

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email raianknight@gmail.com
          git config --global user.name RaiaN
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Install dependencies
        run: |
          yarn
      - name: Deploy to gh-pages
        run: npm run deploy:github
