name: Gatsby Deploy

on:
  push:
    branches: develop

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email raianknight@gmail.com
          git config --global user.name RaiaN
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          yarn
      - name: Deploy
        run: npm run deploy:github